language: java
jdk:
- oraclejdk8
install:
- gradle assemble
script:
- gradle check
deploy:
  provider: heroku
  api_key:
    secure: qfM+yb6WX1hBeqOEyOQswBq8lq+n3ij+wVA04pWYmKQ5a2Ij/rh2Gt6WkxWCSmo2EVYTGmI7GyLYKhas4UYeWf8XctE/5K8wnWJQr2CdPfekR4KQVr8T5D8wjX+qrv3h5k7Yh8MU0trpDiD3kbVFt8ZJhPlsfuLvP+YOqU234OICdCI37v+HJwUNWeWhbDLsaX3fIcrkNksyklM9Qm9lN7ffEmlSrxQBI7vT1xQM/CjQcinnG551aC0QUeRBBYn7GjBScBp7uB5wknLUSZTgEGQ5v1zIeeivR1lg5z3eChWdoUuAEmPx/y8H03hi7PBTXa5UbTdBSHJuzK+kdFjfPDXgmWLeF/OAP46tU8xeGpLsLJ1VZIdrRa4X4qbFkJwwJ4ZLQv5ec93+tQFmLrVVhTumoum4dPTEhwoO5/hoc91+VD/q7cFGAlikP2CsvfHPTcw2kPNZL993Lq+ez3ZgWAHfK8weTdGmFEBK3MeUuAuq3Y0WHJ8Kep/kVTDk6ycrD0VRACzAOKQhV2NTAfyAvuMJleQbT6ZI93JIeoHin9GgY7lj0vGmm+z5EpOtTfxLyVpW5OJlWTxFjL6vEhc2Q5/b/jHKhL3l7TN/0avN3rte/rnu6tVwU6HUGE/1dvXw8hgpSip08v5jOWqxizzTiZZXFEON7ajkLUQUcHY7Vl0=
  app: levonkecommunity
  on:
    repo: matthewpoletin/levonke.Community
    branch: develop
notifications:
  email: false
