language: java
jdk:
- oraclejdk8
install:
- gradle assemble
script:
- gradle check
deploy:
  provider: heroku
  api_key:
    secure: jPLyhHBbozE/fxcIIOtmbZoYQLhTD0J9/qPmZ/91/kvXgGHnlOTD2CVb9VlXvsF18MJ6BKIgrJTGn0dr+jISGVhUG+CSnX0u9MBtjN22xYU2wIh5/MMDyLTHOUJaVTjVS0uWNP9FSvt54N5mh9TIhKhMl3sAISOUe8zt8wLMfyl0s1gXgZ5CMBCnZXXlaiY/Qkv+OsZE83gbJM0bgkcRJp/XdTU6yGmOlCgXGcSOxHi+T7yzUUjzKkDBnCblEug2TDagLIppCM5iuBInZ4OghSaoixGY5llS8ifPSzuZLyH7m5dHdQ+oqX+mjGW183xSnUAGa3JgdWaLAvSnCOMrapOciLThAuV3bXsQMoGguisQ0RMey/n3s9Dh8AFFYVaD0zNhgRVCflr78zgNCj1MRBGlOJjeLOAFhya9SFIU5NWr/CiXvVUKV35JFMv06eBH+EamlyVbj2FoE38gvI1F8J+oMiCec3ntkTenNKkI6rnYJ9KzdZ3grhFCLjq+6nqbNtgmV07BvciPrrcDxgBNGrokrUAonWRwp+hVzyx0aOajJUNa1ATN/jnMb9CdRVI3ek3WifBYcX0dxqXL14jFOg7MD6kEIHiJNyA1rjfP9UCnNDv6/27m03/84P6rN1c2rerxC0O403V/7xbPG1k1c3BSvmSqJACSqSQJYqEVnK4=
  app: levonkecommunity
  on:
    repo: matthewpoletin/levonke-Community
notifications:
  email: false
